seeds: [42]

datasets:
- australian_electricity_demand
- bitcoin
- car_parts
- cif_2016
- covid_deaths
- dominick
- electricity
- exchange_rate
- fred_md
- hospital
- kdd_2018
- london_smart_meters
- m1_monthly
- m1_quarterly
- m1_yearly
- m3_monthly
- m3_other
- m3_quarterly
- m3_yearly
- m4_daily
- m4_hourly
- m4_monthly
- m4_quarterly
- m4_weekly
- m4_yearly
- nn5
- pedestrian_count
- rideshare
- san_francisco_traffic
- solar
- taxi
- temperature_rain
- tourism_monthly
- tourism_quarterly
- tourism_yearly
- vehicle_trips
- weather
- wiki
- wind_farms

models:
  autogluon: 
    - key: presets
      values: [medium_quality]
    - key: run_time
      values: [14400]
    - key: eval_metric
      values: [MASE] # AVAILABLE_METRICS = ["MASE", "MAPE", "sMAPE", "mean_wQuantileLoss", "MSE", "RMSE"]
